In [31]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

a = np.ones([2], dtype="uint8")                             # Created an array, size 2, with two numbers [1, 1]

b = a * 100                                                 # Array [100, 100]

print(b)
print(b + 155)
print(b + 156)

[100 100]
[255 255]
[0 0]


In [35]:
m1 = np.array([[150, 155], [156, 157]], dtype = "uint8")
m2 = np.ones([2, 2], dtype = "uint8") * 100
print("m1:")
print(m1)
print("m2:")
print(m2)
print("m1+m2:")
print(m1 + m2)


m1:
[[150 155]
 [156 157]]
m2:
[[100 100]
 [100 100]]
m1+m2:
[[250 255]
 [  0   1]]
